spring:
  application:
    name: "configserver"
  profiles:
    # below 👇 , you need to activate if you want to use config from local system
    # active: native
    # below 👇, you need to active to use configuration from github
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///D://udemy//spring-boot-learning-microservices-docker-kubernetes//Microservices//section6//config"
        git:
          uri: "https://github.com/erenJaggerMeister/belajar-spring-boot-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "RAYMONDCHIN123THEODERICK456"

server:
  port: 8071