build:
  version: "1.0"

cards:
  message: "This is from prod configuration 'application_prod.yml' "
  contactDetails:
    name: "Marcellius_prod - prod config cards"
    email: "marcellius_prod@example.com"
  onCallSupport:
    - (+62) 823-1697-1400