build:
    version: "2.0"

loans:
    message: "Welcome to loans application_qa.yml related to QA APIs"
    contactDetails:
      name: "Marcellius - junior developer"
      email: "marcellius@gmail.com"
    onCallSupport:
      - (+62) 823-1697-1400